github_checks: true

coverage:
  status:
    patch:
      default:
        # basic
        target: auto #default
        threshold: "5"
        paths:
          - "src/"
    project:
      default:
        # basic
        target: auto #default
        threshold: "5"
        paths:
          - "src/"
