site_name: Kedro Databricks
site_url: https://github.com/JenspederM/kedro-databricks
repo_name: JenspederM/kedro-databricks
repo_url: https://github.com/JenspederM/kedro-databricks
watch:
  - docs
  - src
  - examples
  - scripts
theme:
  name: material
  logo: assets/kedro-databricks-logo.png
  palette:
    scheme: blue grey
    primary: indigo
    accent: indigo

  features:
    - navigation.sections
    - content.tabs.link
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - mkdocs-click
  - toc
plugins:
  - gen-files:
      scripts:
        - scripts/gen_example_pages.py
        - scripts/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: false
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: true
            merge_init_into_class: true
