site_name: Kedro Databricks
site_url: https://github.com/JenspederM/kedro-databricks
repo_name: JenspederM/kedro-databricks
repo_url: https://github.com/JenspederM/kedro-databricks
watch:
  - docs
  - src
  - examples
theme:
  name: material
  features:
    - navigation.tabs
    - content.tabs.link
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - mkdocs-click
  - toc
plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: false
              trim_doctest_flags: true
            merge_init_into_class: true
