nav:
  - Kedro Databricks: index.md
  - Getting Started: getting_started.md
  - Examples:
      - "examples/*"
  - Reference:
      - "reference/*"
  - Contribute:
      - contributing.md
  - changelog.md
