nav:
    - Kedro Databricks: index.md
    - Getting Started: getting_started.md
    - Examples:
          - "examples/*"
    - Reference:
          - "reference/*"
    - contributing.md
    - Changelog: changelog.md
