name: github-pages-deploy
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
      - name: Sync kedro-databricks
        run: |
          uv sync --group docs
      - run: uv run mkdocs gh-deploy --force
