name: Integration Tests
concurrency: "integration"

on:
  push:
    paths:
      - .github/workflows/reusable_integration_tests.yml
    branches:
      - release-please--branches--main

jobs:
  integration:
    name: Run integration tests
    uses: ./.github/workflows/reusable_integration_tests.yml
    with:
      codecov: false
    secrets:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
