name: Unit tests

on:
  pull_request:
    branches-ignore:
      - release-please--branches--main

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
        kedro_version: [ "0.19.7", "0.19.8", "latest" ]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: jdx/mise-action@v3
      - name: Sync kedro-databricks
        run: |
          if [ "${{ matrix.kedro_version }}" = "latest" ]; then
            uv add "kedro"
          else
            uv add "kedro==${{ matrix.kedro_version }}"
          fi
          uv sync --group unit --python ${{ matrix.python-version }}
      - name: Check kedro-databricks
        run: just check
      - name: Test kedro-databricks
        run: just unittest
      - name: Rename coverage file
        run: mv coverage.junit.xml coverage-${{ matrix.kedro_version }}-${{ matrix.python-version }}.junit.xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.kedro_version }}-${{ matrix.python-version }}.junit.xml
          path: coverage-${{ matrix.kedro_version }}-${{ matrix.python-version }}.junit.xml
          if-no-files-found: ignore
  build-pr:
    name: Build PR artifact
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: coverage-*
          path: coverage
          merge-multiple: true

      - name: Create PR artifact
        run: |
          mkdir -p ./pr
          cp -r coverage ./pr/coverage
          cp ${{ github.event_path }} ./pr/event.json
          echo ${{ github.event.pull_request.number }} > ./pr/NR
          ls -la ./pr

      - name: Upload PR artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/
